# Generated by Django 3.1.5 on 2021-01-30 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default='Dog', max_length=3)),
                ('pet_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('pet_breed', models.CharField(max_length=200)),
                ('pet_color', models.CharField(blank=True, max_length=200)),
                ('starting_weight', models.IntegerField()),
                ('pet_birthday', models.DateField()),
                ('pet_allergies', models.CharField(default='none', max_length=300)),
                ('pet_primary_vet', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tracking_type', models.CharField(choices=[('DT', 'Daily_Tracking'), ('VT', 'Vet_visit'), ('EM', 'Emergency')], default='DT', max_length=2)),
                ('pet_weight', models.IntegerField(blank=True)),
                ('pet_temp', models.IntegerField(blank=True)),
                ('solid_stool', models.BooleanField(default=True)),
                ('healthy_appetite', models.BooleanField(default=True)),
                ('healthy_coat', models.BooleanField(default=True)),
                ('range_of_motion_exercises', models.BooleanField(default=True)),
                ('ongoing_meds', models.BooleanField(default=False)),
                ('pet_glucose', models.IntegerField(blank=True)),
                ('acupuncture', models.BooleanField(default=False)),
                ('laser_therapy', models.BooleanField(default=False)),
                ('adjustment', models.BooleanField(default=False)),
                ('surgery', models.BooleanField(default=False)),
                ('special_notes_for_next_time', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('pet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_health_tracker.petinfo')),
            ],
        ),
    ]
