# Generated by Django 3.1.5 on 2021-02-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracker',
            name='pet_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='starting_weight',
            field=models.FloatField(),
        ),
    ]
