# Generated by Django 3.1.5 on 2021-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petinfo',
            options={'verbose_name_plural': 'Pets Information'},
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='pet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
