# Generated by Django 3.1.5 on 2021-01-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_health_tracker', '0002_auto_20210130_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracker',
            name='pet_glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
