# Generated by Django 3.1.5 on 2021-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_health_tracker', '0002_auto_20210206_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracker',
            name='tracking_type',
            field=models.CharField(choices=[('DT', 'Daily Tracking'), ('VT', 'Vet visit'), ('EM', 'Emergency')], default='DT', max_length=2),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='pet_birthday',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
