# Generated by Django 3.1.5 on 2021-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_health_tracker', '0003_auto_20210130_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracker',
            name='pet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='pet_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
