# Generated by Django 3.1.5 on 2021-02-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_health_tracker', '0004_auto_20210130_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracker',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='special_notes_for_next_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
